name: habit_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

  # الإشعارات
  flutter_local_notifications: ^22.3.0

  # تشغيل ومعاينة أصوات التنبيهات
  audioplayers: ^6.8.1

  # جدولة الإشعارات حسب المنطقة الزمنية
  timezone: ^0.11.1

  # حزم الفايربيس الجديدة التي تم إضافتها
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/sounds/