// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpTG5JhRf7_rcKxwhzHM8i57rysTB528E',
    appId: '1:993504363205:web:ee2e0b0a3ec6b78a8ea6ac',
    messagingSenderId: '993504363205',
    projectId: 'habittrackerapp-231e2',
    authDomain: 'habittrackerapp-231e2.firebaseapp.com',
    storageBucket: 'habittrackerapp-231e2.firebasestorage.app',
    measurementId: 'G-KMC2VN88T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERyMLz4ycKXeltyvp87fkvK9gmvA4rr4',
    appId: '1:993504363205:android:2a169173835c897e8ea6ac',
    messagingSenderId: '993504363205',
    projectId: 'habittrackerapp-231e2',
    storageBucket: 'habittrackerapp-231e2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpTG5JhRf7_rcKxwhzHM8i57rysTB528E',
    appId: '1:993504363205:web:91eaaa16c6a5ba028ea6ac',
    messagingSenderId: '993504363205',
    projectId: 'habittrackerapp-231e2',
    authDomain: 'habittrackerapp-231e2.firebaseapp.com',
    storageBucket: 'habittrackerapp-231e2.firebasestorage.app',
    measurementId: 'G-BXFFFPBB7M',
  );
}
